package br.com.view;

import br.com.controller.FundoImagem;
import br.com.model.GerenciamentoTelaModel;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Diego Danniel
 */
public final class FormPrincipal extends JFrame {

    private static FormAcessoRestrito acessos;
    private static final long serialVersionUID = 1L;
    
    String seta_look = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel"; //"com.sun.java.swing.plaf.motif.MotifLookAndFeel";

    /*Buscando o caminho da logotipo do sistema*/
    public InputStream foto1 = this.getClass().getResourceAsStream("SysmacLogo.png");

    /**
     * Creates new form Tela_Principal
     */
    public FormPrincipal() {
        initComponents();
       // lookandfeel();
        caregarImagen(desktop, foto1);
        //gerenciamentoTelas = new GerenciamentoTelaModel(desktop);
       
    }
    

  
    public void logoff(){
        FormLogin login = new FormLogin();
        login.setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*Metodo desenvolvido para a chamada de tela em modal para acesso restrito*/
    public void chamarTelaAcessoRestrito() {
        acessos = new FormAcessoRestrito(this, true);
        acessos.setVisible(true);
    }

    public void chamarTelaConfiguracao() {
        GerenciamentoTelaModel gerenciamentoTelas = new GerenciamentoTelaModel(desktop);
        gerenciamentoTelas.abrirJanelas(FormConfiguracaoSistema.getConfiguracaoSistema());
    }

 
    
    
    public void chamarTelaCadastroCasas(){
       
        GerenciamentoTelaModel gerenciamentoTelas = new GerenciamentoTelaModel(desktop);
        gerenciamentoTelas.abrirJanelas(FormCasas.getCasasCadastro());
        
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jblUsuarioConectado = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        jToolBarPrincipal = new javax.swing.JToolBar();
        btnAtCliente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jblEmpresaNome = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuCadastroPrincipal = new javax.swing.JMenu();
        MenuCadastroCliente = new javax.swing.JMenuItem();
        MenuCadastroFornecedores = new javax.swing.JMenuItem();
        MenuCadastroCasas = new javax.swing.JMenuItem();
        MenuCadastroFuncionariosEUsuarios = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenuGerenciadorPrincipal = new javax.swing.JMenu();
        MenuAlugueisPrincipal = new javax.swing.JMenu();
        MenuAlugarCasa = new javax.swing.JMenuItem();
        MenuCadastroProdutos = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        MenuEmailPrincipal = new javax.swing.JMenu();
        MenuEmailGerenciador = new javax.swing.JMenuItem();
        MenuFinanceiroPrincipal = new javax.swing.JMenu();
        MenuContasAReceber = new javax.swing.JMenu();
        MenuContasAReceberLancamentos = new javax.swing.JMenuItem();
        MenuContasAReceberRecebimentos = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        MenuRelatoriosPrincipal = new javax.swing.JMenu();
        MenuRelatoriosClientesPrincipal = new javax.swing.JMenu();
        MenuRelatoriosClientesGeral = new javax.swing.JMenuItem();
        MenuRelatoriosClientesAniversario = new javax.swing.JMenuItem();
        MenuRelatoriosClientesFiadores = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuPrincipalConfiguracao = new javax.swing.JMenu();
        MenuConfiguracao = new javax.swing.JMenu();
        MenuConfiguracaoParametros = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuConfiguracaoBackup = new javax.swing.JMenu();
        MenuBackupIniciar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Imobiliario");
        setExtendedState(6);
        setName("TelaPrincipal"); // NOI18N

        jblUsuarioConectado.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblUsuarioConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jblUsuarioConectado))
        );

        desktop.setBackground(java.awt.Color.darkGray);
        desktop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                desktopMouseMoved(evt);
            }
        });

        jToolBarPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Menu Rápido"));
        jToolBarPrincipal.setRollover(true);

        btnAtCliente.setText("Clientes");
        btnAtCliente.setFocusable(false);
        btnAtCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAtClienteMouseMoved(evt);
            }
        });
        btnAtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtClienteActionPerformed(evt);
            }
        });
        jToolBarPrincipal.add(btnAtCliente);

        jButton2.setText("Casas");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBarPrincipal.add(jButton2);

        jButton3.setText("Fiadores");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarPrincipal.add(jButton3);

        jButton4.setText("Bancos");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarPrincipal.add(jButton4);

        jButton1.setText("Agenda");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarPrincipal.add(jButton1);

        jblEmpresaNome.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jblEmpresaNome.setForeground(new java.awt.Color(255, 255, 255));
        jblEmpresaNome.setText("Imobiliário");
        jblEmpresaNome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jblEmpresaNomeMouseMoved(evt);
            }
        });

        desktop.setLayer(jToolBarPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jblEmpresaNome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addComponent(jToolBarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 466, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jblEmpresaNome)))
                .addContainerGap())
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addComponent(jToolBarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(jblEmpresaNome)
                .addContainerGap())
        );

        jMenu1.setText("Inicio");

        MenuCadastroPrincipal.setText("Cadastros");

        MenuCadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        MenuCadastroCliente.setText("Clientes");
        MenuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroClienteActionPerformed(evt);
            }
        });
        MenuCadastroPrincipal.add(MenuCadastroCliente);

        MenuCadastroFornecedores.setText("Fornecedores");
        MenuCadastroFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroFornecedoresActionPerformed(evt);
            }
        });
        MenuCadastroPrincipal.add(MenuCadastroFornecedores);

        MenuCadastroCasas.setText("Casas");
        MenuCadastroCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroCasasActionPerformed(evt);
            }
        });
        MenuCadastroPrincipal.add(MenuCadastroCasas);

        MenuCadastroFuncionariosEUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuCadastroFuncionariosEUsuarios.setText("Funcionarios e Usuarios");
        MenuCadastroFuncionariosEUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroFuncionariosEUsuariosActionPerformed(evt);
            }
        });
        MenuCadastroPrincipal.add(MenuCadastroFuncionariosEUsuarios);

        jMenu1.add(MenuCadastroPrincipal);

        jMenu6.setText("Empresa");
        jMenu1.add(jMenu6);

        MenuPrincipal.add(jMenu1);

        MenuGerenciadorPrincipal.setText("Gerenciador");

        MenuAlugueisPrincipal.setText("Alugueis");

        MenuAlugarCasa.setText("Alugar");
        MenuAlugarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAlugarCasaActionPerformed(evt);
            }
        });
        MenuAlugueisPrincipal.add(MenuAlugarCasa);

        MenuGerenciadorPrincipal.add(MenuAlugueisPrincipal);

        MenuCadastroProdutos.setText("Produtos");

        jMenuItem10.setText("Cadastros");
        MenuCadastroProdutos.add(jMenuItem10);

        MenuGerenciadorPrincipal.add(MenuCadastroProdutos);

        MenuEmailPrincipal.setText("E-mail");

        MenuEmailGerenciador.setText("Gerenciador");
        MenuEmailPrincipal.add(MenuEmailGerenciador);

        MenuGerenciadorPrincipal.add(MenuEmailPrincipal);

        MenuPrincipal.add(MenuGerenciadorPrincipal);

        MenuFinanceiroPrincipal.setText("Financeiro");

        MenuContasAReceber.setText("Contas a Receber");

        MenuContasAReceberLancamentos.setText("Lançamentos");
        MenuContasAReceber.add(MenuContasAReceberLancamentos);

        MenuContasAReceberRecebimentos.setText("Recebimentos");
        MenuContasAReceberRecebimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuContasAReceberRecebimentosActionPerformed(evt);
            }
        });
        MenuContasAReceber.add(MenuContasAReceberRecebimentos);

        MenuFinanceiroPrincipal.add(MenuContasAReceber);

        jMenu8.setText("Contas a Pagar");

        jMenuItem7.setText("Lançamentos");
        jMenu8.add(jMenuItem7);

        jMenuItem8.setText("Pagamento de contas");
        jMenu8.add(jMenuItem8);

        MenuFinanceiroPrincipal.add(jMenu8);

        MenuPrincipal.add(MenuFinanceiroPrincipal);

        MenuRelatoriosPrincipal.setText("Relatórios");

        MenuRelatoriosClientesPrincipal.setText("Clientes");

        MenuRelatoriosClientesGeral.setText("Clientes Geral");
        MenuRelatoriosClientesGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatoriosClientesGeralActionPerformed(evt);
            }
        });
        MenuRelatoriosClientesPrincipal.add(MenuRelatoriosClientesGeral);

        MenuRelatoriosClientesAniversario.setText("Clientes Aniversário");
        MenuRelatoriosClientesPrincipal.add(MenuRelatoriosClientesAniversario);

        MenuRelatoriosClientesFiadores.setText("Clientes Fiadores");
        MenuRelatoriosClientesPrincipal.add(MenuRelatoriosClientesFiadores);

        MenuRelatoriosPrincipal.add(MenuRelatoriosClientesPrincipal);

        jMenu16.setText("Casas");

        jMenuItem17.setText("Alugadas");
        jMenu16.add(jMenuItem17);

        jMenuItem18.setText("Não alugadas");
        jMenu16.add(jMenuItem18);

        jMenuItem19.setText("Todas");
        jMenu16.add(jMenuItem19);

        MenuRelatoriosPrincipal.add(jMenu16);

        jMenuItem4.setText("Usuários");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuRelatoriosPrincipal.add(jMenuItem4);

        MenuPrincipal.add(MenuRelatoriosPrincipal);

        MenuPrincipalConfiguracao.setText("Configurações e Ações");

        MenuConfiguracao.setText("Configurações");

        MenuConfiguracaoParametros.setText("Parâmetros");
        MenuConfiguracaoParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConfiguracaoParametrosActionPerformed(evt);
            }
        });
        MenuConfiguracao.add(MenuConfiguracaoParametros);

        jMenuItem3.setText("Configurações");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuConfiguracao.add(jMenuItem3);

        MenuPrincipalConfiguracao.add(MenuConfiguracao);

        MenuConfiguracaoBackup.setText("Backup de Dados");

        MenuBackupIniciar.setText("Iniciar Backup");
        MenuConfiguracaoBackup.add(MenuBackupIniciar);

        MenuPrincipalConfiguracao.add(MenuConfiguracaoBackup);

        MenuPrincipal.add(MenuPrincipalConfiguracao);

        jMenu2.setText("Logoff");

        jMenuItem1.setText("Usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Sair");
        jMenu2.add(jMenuItem2);

        MenuPrincipal.add(jMenu2);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desktop))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Tela Principal");

        setSize(new java.awt.Dimension(765, 404));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadastroFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCadastroFornecedoresActionPerformed

    private void MenuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroClienteActionPerformed
        // TODO add your handling code here:
        FormClientes clientes = new FormClientes();
        clientes.setVisible(true);
        desktop.add(clientes);
    }//GEN-LAST:event_MenuCadastroClienteActionPerformed

    private void jblEmpresaNomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblEmpresaNomeMouseMoved
        // TODO add your handling code here:
        jblEmpresaNome.setForeground(new Color(255, 115, 28));
    }//GEN-LAST:event_jblEmpresaNomeMouseMoved

    private void desktopMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopMouseMoved
        // TODO add your handling code here:
        jblEmpresaNome.setForeground(Color.WHITE);

    }//GEN-LAST:event_desktopMouseMoved

    private void btnAtClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtClienteMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAtClienteMouseMoved

    private void MenuRelatoriosClientesGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatoriosClientesGeralActionPerformed
        // TODO add your handling code here:
        FormRelatoriosClientesGeral rtl = new FormRelatoriosClientesGeral();
        rtl.setVisible(true);
        desktop.add(rtl);
    }//GEN-LAST:event_MenuRelatoriosClientesGeralActionPerformed

    private void MenuCadastroCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroCasasActionPerformed
        // TODO add your handling code here:
     chamarTelaAcessoRestrito();
    }//GEN-LAST:event_MenuCadastroCasasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        GerenciamentoTelaModel gerenciamentoTelas = new GerenciamentoTelaModel(desktop);
        gerenciamentoTelas.abrirJanelas(FormCasas.getCasasCadastro());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtClienteActionPerformed
        // TODO add your handling code here:
        FormClientes clientes = new FormClientes();
        clientes.setVisible(true);
        desktop.add(clientes);
    }//GEN-LAST:event_btnAtClienteActionPerformed

    private void MenuContasAReceberRecebimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuContasAReceberRecebimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuContasAReceberRecebimentosActionPerformed

    private void MenuConfiguracaoParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConfiguracaoParametrosActionPerformed
        // TODO add your handling code here:
        FormAcessosDeUsuarios acesso = new FormAcessosDeUsuarios();
        acesso.setVisible(true);
        desktop.add(acesso);
    }//GEN-LAST:event_MenuConfiguracaoParametrosActionPerformed

    private void MenuCadastroFuncionariosEUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroFuncionariosEUsuariosActionPerformed
        // TODO add your handling code here:
        GerenciamentoTelaModel gerenciamentoTelas = new GerenciamentoTelaModel(desktop);
        gerenciamentoTelas.abrirJanelas(FormUsuarios.getCadUsuarios());

    }//GEN-LAST:event_MenuCadastroFuncionariosEUsuariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        logoff();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        chamarTelaAcessoRestrito();

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        FormRelatorioUsuario user = new FormRelatorioUsuario();
        user.setVisible(true);
        desktop.add(user);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void MenuAlugarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAlugarCasaActionPerformed
        // TODO add your handling code here:
        FormAluguelCasa casasAlugadas = new FormAluguelCasa();
        casasAlugadas.setVisible(true);
        desktop.add(casasAlugadas);
    }//GEN-LAST:event_MenuAlugarCasaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }
       public JDesktopPane getDesktop() {
        return desktop;
    }

    public void setDesktop(JDesktopPane desktop) {
        this.desktop = desktop;
    }
      public void lookandfeel() {
        try {
            UIManager.setLookAndFeel(seta_look);
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
            // UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }

   

    /**
     *
     * @param jDeskp
     * @param fileImagen
     */
    public void caregarImagen(javax.swing.JDesktopPane jDeskp, InputStream fileImagen) {
        try {
            BufferedImage image = ImageIO.read(fileImagen);
            jDeskp.setBorder(new FundoImagem(image));
        } catch (IOException e) {
            System.out.println("Imagem do sistema não disponiovel ");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAlugarCasa;
    private javax.swing.JMenu MenuAlugueisPrincipal;
    private javax.swing.JMenuItem MenuBackupIniciar;
    private javax.swing.JMenuItem MenuCadastroCasas;
    private javax.swing.JMenuItem MenuCadastroCliente;
    private javax.swing.JMenuItem MenuCadastroFornecedores;
    private javax.swing.JMenuItem MenuCadastroFuncionariosEUsuarios;
    private javax.swing.JMenu MenuCadastroPrincipal;
    private javax.swing.JMenu MenuCadastroProdutos;
    private javax.swing.JMenu MenuConfiguracao;
    private javax.swing.JMenu MenuConfiguracaoBackup;
    private javax.swing.JMenuItem MenuConfiguracaoParametros;
    private javax.swing.JMenu MenuContasAReceber;
    private javax.swing.JMenuItem MenuContasAReceberLancamentos;
    private javax.swing.JMenuItem MenuContasAReceberRecebimentos;
    private javax.swing.JMenuItem MenuEmailGerenciador;
    private javax.swing.JMenu MenuEmailPrincipal;
    private javax.swing.JMenu MenuFinanceiroPrincipal;
    private javax.swing.JMenu MenuGerenciadorPrincipal;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu MenuPrincipalConfiguracao;
    private javax.swing.JMenuItem MenuRelatoriosClientesAniversario;
    private javax.swing.JMenuItem MenuRelatoriosClientesFiadores;
    private javax.swing.JMenuItem MenuRelatoriosClientesGeral;
    private javax.swing.JMenu MenuRelatoriosClientesPrincipal;
    private javax.swing.JMenu MenuRelatoriosPrincipal;
    private javax.swing.JButton btnAtCliente;
    public javax.swing.JDesktopPane desktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBarPrincipal;
    private javax.swing.JLabel jblEmpresaNome;
    public javax.swing.JLabel jblUsuarioConectado;
    // End of variables declaration//GEN-END:variables
}
